### ISSUE TITLE
TLWN722N USB wireless card support?

### ISSUE THREAD

**Issue by LuckyFishGeek** [kaplan2539/CHIP-Debian-Kernel#1]
My device is Pocketchip! I browsed a lot of posts on the compiled kernel in the forum and tried to compile a kernel that supports USB wireless card! But because of my bad technology, I have failed!

If you have a good tutorial on compiling the kernel, please send it to me! Thank you very much for your work.

**Comment by LuckyFishGeek** [comment]
My kernel is 4.4.13-ntc-mlc

**Comment by rampageservices** [comment]
Hi @EastwindZL This page is a good place to start to learn how to compile your own module. There are a few gotchas but you'll end up with a good module once you get all the pieces together. http://www.chip-community.org/index.php/How-To_Build_Just_One_Kernel_Module
